# Generated by Django 4.2.17 on 2025-11-24 20:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate", models.CharField(max_length=10, unique=True)),
                ("type", models.CharField(max_length=20)),
                ("owner", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(default="active", max_length=12)),
                ("tech_review_due", models.DateField(blank=True, null=True)),
                (
                    "capacity_kg",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AccessRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=120)),
                ("driver_rut", models.CharField(max_length=12)),
                ("load_type", models.CharField(max_length=30)),
                ("origin", models.CharField(max_length=120)),
                ("destination", models.CharField(max_length=120)),
                ("state", models.CharField(default="en_planta", max_length=20)),
                ("gate_in_at", models.DateTimeField(auto_now_add=True)),
                ("gate_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_records",
                        to="app_ingreso_salidas.vehicle",
                    ),
                ),
            ],
        ),
    ]
